### ISSUE TITLE
Error CacheProvider - React Native

### ISSUE THREAD

**Issue by angelopedroso** [reactive/data-client#3079]
Describe the bug
Use of default <CacheProvider /> makes React Native app crash.

Text strings must be rendered within a <Text> component.

**Comment by ntucker** [comment]
Can you try with @data-client/react@0.12.11 and share the stack trace here? I changed the name of the .native.js modules so we can determine if the build system is correctly picking up those files.

**Comment by angelopedroso** [comment]
> @angelopedroso Can you try with @data-client/react@0.12.11 and share the stack trace here? I changed the name of the .native.js modules so we can determine if the build system is correctly picking up those files.

Ok, I'll try it as soon as possible 😃, thanks

**Comment by ntucker** [comment]
@angelopedroso This should be fixed in [@data-client/react@0.13.4](https://github.com/reactive/data-client/releases/tag/%40data-client%2Freact%400.13.4)

I went through the process of starting my own expo project to explore this. For some reason the bundler has issues when you specify .js extensions explicitly - but this is necessary for nodejs compatibility with ESM. To workaround I simply added a special build for react-native. This is included in the above release. I just tested it in my project and it works for me - so I hope it does for you too!
